import BanjoKazooie from "../resources/characters/BanjoKazooie.png";
import Bayonetta from "../resources/characters/Bayonetta.png";
import Bowser from "../resources/characters/Bowser.png";
import BowserJr from "../resources/characters/BowserJr.png";
import Byleth from "../resources/characters/Byleth.png";
import CaptainFalcon from "../resources/characters/CaptainFalcon.png";
import Chrom from "../resources/characters/Chrom.png";
import Cloud from "../resources/characters/Cloud.png";
import Corrin from "../resources/characters/Corrin.png";
import Daisy from "../resources/characters/Daisy.png";
import DarkPit from "../resources/characters/DarkPit.png";
import DarkSamus from "../resources/characters/DarkSamus.png";
import DiddyKong from "../resources/characters/DiddyKong.png";
import DonkeyKong from "../resources/characters/DonkeyKong.png";
import DrMario from "../resources/characters/DrMario.png";
import DuckHunt from "../resources/characters/DuckHunt.png";
import Falco from "../resources/characters/Falco.png";
import Fox from "../resources/characters/Fox.png";
import Ganondorf from "../resources/characters/Ganondorf.png";
import Greninja from "../resources/characters/Greninja.png";
import IceClimbers from "../resources/characters/IceClimbers.png";
import Ike from "../resources/characters/Ike.png";
import Incineroar from "../resources/characters/Incineroar.png";
import Inkling from "../resources/characters/Inkling.png";
import Isabelle from "../resources/characters/Isabelle.png";
import Jigglypuff from "../resources/characters/Jigglypuff.png";
import Joker from "../resources/characters/Joker.png";
import Ken from "../resources/characters/Ken.png";
import KingDedede from "../resources/characters/KingDedede.png";
import KingKRool from "../resources/characters/KingKRool.png";
import Kirby from "../resources/characters/Kirby.png";
import Link from "../resources/characters/Link.png";
import LittleMac from "../resources/characters/LittleMac.png";
import Lucario from "../resources/characters/Lucario.png";
import Lucas from "../resources/characters/Lucas.png";
import Lucina from "../resources/characters/Lucina.png";
import Luigi from "../resources/characters/Luigi.png";
import Hero from "../resources/characters/Hero.png";
import PacMan from "../resources/characters/PacMan.png";
import Mario from "../resources/characters/Mario.png";
import Marth from "../resources/characters/Marth.png";
import MegaMan from "../resources/characters/MegaMan.png";
import MetaKnight from "../resources/characters/MetaKnight.png";
import Mewtwo from "../resources/characters/Mewtwo.png";
import MiiBrawler from "../resources/characters/MiiBrawler.png";
import MiiGunner from "../resources/characters/MiiGunner.png";
import MiiSwordfighter from "../resources/characters/MiiSwordfighter.png";
import MinMin from "../resources/characters/MinMin.png";
import MrGameWatch from "../resources/characters/MrGameWatch.png";
import Ness from "../resources/characters/Ness.png";
import Olimar from "../resources/characters/Olimar.png";
import Palutena from "../resources/characters/Palutena.png";
import Peach from "../resources/characters/Peach.png";
import Pichu from "../resources/characters/Pichu.png";
import Pikachu from "../resources/characters/Pikachu.png";
import PiranhaPlant from "../resources/characters/PiranhaPlant.png";
import Pit from "../resources/characters/Pit.png";
import PokemonTrainer from "../resources/characters/PokemonTrainer.png";
import RichterBelmont from "../resources/characters/RichterBelmont.png";
import Ridley from "../resources/characters/Ridley.png";
import ROB from "../resources/characters/ROB.png";
import Robin from "../resources/characters/Robin.png";
import RosalinaLuma from "../resources/characters/RosalinaLuma.png";
import Roy from "../resources/characters/Roy.png";
import Ryu from "../resources/characters/Ryu.png";
import Samus from "../resources/characters/Samus.png";
import Sheik from "../resources/characters/Sheik.png";
import Shulk from "../resources/characters/Shulk.png";
import SimonBelmont from "../resources/characters/SimonBelmont.png";
import Snake from "../resources/characters/Snake.png";
import Sonic from "../resources/characters/Sonic.png";
import Terry from "../resources/characters/Terry.png";
import ToonLink from "../resources/characters/ToonLink.png";
import Villager from "../resources/characters/Villager.png";
import Wario from "../resources/characters/Wario.png";
import WiiFitTrainer from "../resources/characters/WiiFitTrainer.png";
import Wolf from "../resources/characters/Wolf.png";
import Yoshi from "../resources/characters/Yoshi.png";
import YoungLink from "../resources/characters/YoungLink.png";
import Zelda from "../resources/characters/Zelda.png";
import ZeroSuitSamus from "../resources/characters/ZeroSuitSamus.png";
import Steve from "../resources/characters/Steve.png";



export { BanjoKazooie }
export { Bayonetta }
export { Bowser }
export { BowserJr }
export { Byleth }
export { CaptainFalcon }
export { Chrom }
export { Cloud }
export { Corrin }
export { Daisy }
export { DarkPit }
export { DarkSamus }
export { DiddyKong }
export { DonkeyKong }
export { DrMario }
export { DuckHunt }
export { Falco }
export { Fox }
export { Ganondorf }
export { Greninja }
export { IceClimbers }
export { Ike }
export { Incineroar }
export { Inkling }
export { Isabelle }
export { Jigglypuff }
export { Joker }
export { Ken }
export { KingDedede }
export { KingKRool }
export { Kirby }
export { Link }
export { LittleMac }
export { Lucario }
export { Lucas }
export { Lucina }
export { Luigi }
export { Hero }
export { PacMan }
export { Mario }
export { Marth }
export { MegaMan }
export { MetaKnight }
export { Mewtwo }
export { MiiBrawler }
export { MiiGunner }
export { MiiSwordfighter }
export { MinMin }
export { MrGameWatch }
export { Ness }
export { Olimar }
export { Palutena }
export { Peach }
export { Pichu }
export { Pikachu }
export { PiranhaPlant }
export { Pit }
export { PokemonTrainer }
export { RichterBelmont }
export { Ridley }
export { ROB }
export { Robin }
export { RosalinaLuma }
export { Roy }
export { Ryu }
export { Samus }
export { Sheik }
export { Shulk }
export { SimonBelmont }
export { Snake }
export { Sonic }
export { Terry }
export { ToonLink }
export { Villager }
export { Wario }
export { WiiFitTrainer }
export { Wolf }
export { Yoshi }
export { YoungLink }
export { Zelda }
export { ZeroSuitSamus }
export { Steve }